# Generated by Django 4.1.4 on 2023-04-01 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(max_length=50)),
            ],
        ),
    ]
